-- Create table for storing generated pages
create table generated_pages (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  type text not null, -- 'simple' or 'landing'
  goal text,
  prompt text,
  content jsonb not null
);

-- Create table for storing leads captured from the generated forms
create table leads (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  email text not null,
  page_id bigint references generated_pages(id),
  metadata jsonb
);

-- Enable Row Level Security (RLS) if needed, or leave open for MVP (be careful in production)
-- For MVP, we might want to allow public insert for leads if the form is public
alter table leads enable row level security;

create policy "Enable insert for all users"
on leads for insert
with check (true);

-- For generated_pages, we might want to allow read/write for authenticated users or just public for this MVP demo
alter table generated_pages enable row level security;

create policy "Enable read access for all users"
on generated_pages for select
using (true);

create policy "Enable insert for all users"
on generated_pages for insert
with check (true);
